/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/tidox-theme.ts
 * Command: astryx theme build theme/tidox-theme.ts --out src/styles/tidox-theme.css
 * Generated: 2026-09-24T23:27:08.105Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const tidoxTheme: DefinedTheme;
