/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: theme/tidox-theme.ts
 * Command: astryx theme build theme/tidox-theme.ts --out src/styles/tidox-theme.css
 * Generated: 2026-07-18T15:02:10.100Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
